export const countryToCode = {
  "Marrocos": "ma",
  "Chile": "cl",
  "Brasil": "br",
  "Argentina": "ar",
  "Alemanha": "de",
  "França": "fr",
  "Japão": "jp",
  "Coreia do Sul": "kr",
  "México": "mx",
  "Inglaterra": "gb-eng",
  "Portugal": "pt",
  "Espanha": "es",
  "Holanda": "nl",
  "Uruguai": "uy",
  "Senegal": "sn",
  "Estados Unidos": "us",
  "Croácia": "hr",
  "Bélgica": "be",
  "Suíça": "ch",
  "Camarões": "cm",
  "Sérvia": "rs",
  "Gana": "gh",
  "Canadá": "ca",
  "Catar": "qa",
  "Equador": "ec",
  "Arábia Saudita": "sa",
  "Irã": "ir",
  "Austrália": "au",
  "Dinamarca": "dk",
  "Tunísia": "tn",
  "Polônia": "pl",
  "Costa Rica": "cr",
  "Jamaica": "jm",
  "Colômbia": "co",
  "Iraque": "iq",
  "Indonésia": "id",
  "Turquia": "tr",
  "Venezuela": "ve",
  "Argélia": "dz",
  "Nigéria": "ng",
  "Panamá": "pa",
  "Escócia": "gb-sct",
  "Hungria": "hu",
  "Áustria": "at",
  "Jordânia": "jo",
  "Uzbequistão": "uz",
  "Nova Zelândia": "nz",
  "Costa do Marfim": "ci",
  "Itália": "it",
  "Suécia": "se",
  "Egito": "eg",
  "Paraguai": "py",
  "Peru": "pe"
};